server=ncr-mt2-en-us-qa.kitsys.net
protocol=https
port=8090
nbt_directory=../common/
nbt_token_location=../commmon/token_nbt_file.csv

jmeter.save.saveservice.output_format=csv
# Ensure all required fields are saved
jmeter.save.saveservice.timestamp=true
jmeter.save.saveservice.elapsed=true
jmeter.save.saveservice.label=true
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.response_message=true
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.grpThreads=true
jmeter.save.saveservice.allThreads=true
jmeter.save.saveservice.latency=true

# Disable extra fields (optional, if you suspect issues from them)
jmeter.save.saveservice.connect_time=false
jmeter.save.saveservice.sent_bytes=false
jmeter.save.saveservice.thread_name=false
jmeter.save.saveservice.data_type=false
jmeter.save.saveservice.failure_message=false

jmeter.reportgenerator.apdex_satisfied_threshold=500
jmeter.reportgenerator.apdex_tolerated_threshold=1500

jmeter.save.saveservice.thread_name=true